#pragma config(Sensor, S1,     touchLeft,      sensorTouch)
#pragma config(Sensor, S2,     touchRight,     sensorTouch)
#pragma config(Sensor, S3,     distance,       sensorSONAR)
#pragma config(Motor,  motorA,          motorRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "SimpleMotorLib.h"
#include "SimpleWaitLib.h"

task main()
{
	int SPEED = 127;
	int ROTATION_DEGREES = 350;
	int MAX_DISTANCE = 30;
	int MIN_DISTANCE = 10;
	while(true){
	 	if(SensorValue(distance) <= MAX_DISTANCE){
	 		bool right = (((rand() % (10-0)) + 0) % 2 == 0);

	 		//Ferma i motori
			stopMotor(motorLeft);
			stopMotor(motorRight);

			if(SensorValue(distance) <= MIN_DISTANCE){
				goMotorStandard(motorRight,-SPEED);
		 		goMotorStandard(motorLeft,-SPEED);

		 		wait(1);
			}

			if(right){
					//Va a destra
				goMotorDegrees(motorLeft,ROTATION_DEGREES,SPEED);
			}
			else{
				goMotorDegrees(motorRight,ROTATION_DEGREES,SPEED);
			}
	 	}

		if(SensorValue(touchLeft)){
			//Va indietro
	 		goMotorStandard(motorRight,-SPEED);
	 		goMotorStandard(motorLeft,-SPEED);

	 		wait(1);

	 		//Ferma i motori
			stopMotor(motorLeft);
			stopMotor(motorRight);

			//Va a destra
			goMotorDegrees(motorLeft,ROTATION_DEGREES,SPEED);

		}
		else if(SensorValue(touchRight)){
			//Va indietro
	 		goMotorStandard(motorRight,-SPEED);
	 		goMotorStandard(motorLeft,-SPEED);

	 		wait(1);

	 		//Ferma i motori
			stopMotor(motorLeft);
			stopMotor(motorRight);

			//Va a destra
			goMotorDegrees(motorRight,ROTATION_DEGREES,SPEED);
	 	}
		else if(SensorValue(touchRight) && SensorValue(touchLeft)){
			//Va indietro e gira a random tra destra e sinistra di 90 gradi
		}
		else{
			//Controlla ultrasuoni
			goMotorStandard(motorRight,SPEED);
			goMotorStandard(motorLeft,SPEED);
		}
	}
	/*
	*/
}
