#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "simpleTouchLib.h"
#include "simpleMotorLib.h"

task main()
{
		while(true){
			if(isPressed(touchSensor)){
				writeDebugStreamLine("1");
			}
			else{
				writeDebugStreamLine("0");
			}
		}
}
