#pragma config(Sensor, S1,     microphoneSensor, sensorSoundDB)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorC,          bigMotor,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "SimpleTouchLib.h"
#include "SimpleMotorLib.h"
#include "SimpleWaitLib.h"

task main()
{
	//waitTime -> Worka
	//waitDistance -> Worka
	//waitTouch -> Worka

	goMotor(bigMotor);
	//waitMicrophone(microphoneSensor,10,0);
	waitNxtButtons(3);
	nVolume = 4;
	PlaySound(soundBeepBeep);
	wait(2);
}
