#pragma config(Sensor, S1,     microphoneSensor, sensorSoundDB)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          bigMotor,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "SimpleMotorLib.h"
#include "SimpleWaitLib.h"

task main()
{
	//waitTime -> Worka
	//waitDistance -> Worka
	//waitTouch -> Worka
	//waitMicrophone -> Worka
	//waitColor -> Worka

	//goMotor(bigMotor);

	//Sets the motorA's target to 1000 encoder counts at a speed value of 50
 	setMotorTarget(bigMotor, 500, 50);

 	//Holds program flow until the motor on motor port A comes to a complete stop.
 	waitUntilMotorStop(bigMotor);

	//wait(2);
	//stopMotor(bigMotor,1);

}
